<?php

/***************************************************
 * トップ画面
 *
 *
 * @package
 * @access  public
 * @author  
 * @create  
 * @version 
 ***************************************************/

require_once('common/base_model_front_base.inc');

require_once('mw_sql.inc');


class mw_index extends base_model_front_base {

    //処理
    public function execute_auth() {
    }

} // end of class
